import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TopbarMenu } from "@/components/ui/topbar-menu";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
}); 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="pt-BR"
      className={cn(inter.variable, geistSans.variable, geistMono.variable, "bg-white text-black")}
    >

      <body className=" w-260 m-auto">
        <TopbarMenu />
        {children}
      </body>
    </html>
  );
}
